-- Execute este arquivo completo no SQL Editor do projeto Supabase.
-- Ele cria (ou atualiza) o bucket público e configura as políticas do álbum.

insert into storage.buckets (
  id,
  name,
  public,
  file_size_limit,
  allowed_mime_types
)
values (
  'casamento-fotos',
  'casamento-fotos',
  true,
  31457280,
  array[
    'image/jpeg',
    'image/png',
    'image/webp',
    'image/gif',
    'image/heic',
    'image/heif'
  ]::text[]
)
on conflict (id) do update
set
  name = excluded.name,
  public = excluded.public,
  file_size_limit = excluded.file_size_limit,
  allowed_mime_types = excluded.allowed_mime_types;

do $$
begin
  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Convidados podem listar fotos do casamento'
  ) then
    execute $policy$
      create policy "Convidados podem listar fotos do casamento"
      on storage.objects
      for select
      to anon, authenticated
      using (
        bucket_id = 'casamento-fotos'
        and (storage.foldername(name))[1] = 'uploads'
      )
    $policy$;
  end if;

  if not exists (
    select 1
    from pg_policies
    where schemaname = 'storage'
      and tablename = 'objects'
      and policyname = 'Convidados podem enviar fotos do casamento'
  ) then
    execute $policy$
      create policy "Convidados podem enviar fotos do casamento"
      on storage.objects
      for insert
      to anon, authenticated
      with check (
        bucket_id = 'casamento-fotos'
        and (storage.foldername(name))[1] = 'uploads'
      )
    $policy$;
  end if;
end
$$;

-- Reações das fotos. A tabela não é exposta diretamente: os convidados usam
-- somente as funções abaixo, que retornam totais agregados e a própria reação.
create table if not exists public.photo_reactions (
  id bigint generated by default as identity primary key,
  photo_id text not null check (char_length(photo_id) between 1 and 128),
  visitor_id uuid not null,
  reaction text not null check (reaction in ('love', 'joy', 'heart_eyes', 'moved', 'celebrate')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (photo_id, visitor_id)
);

create index if not exists photo_reactions_photo_id_idx
  on public.photo_reactions (photo_id);

alter table public.photo_reactions enable row level security;
revoke all on table public.photo_reactions from anon, authenticated;

create or replace function public.get_photo_reactions(
  p_photo_ids text[],
  p_visitor_id uuid
)
returns table (
  photo_id text,
  reaction text,
  reaction_count bigint,
  reacted_by_me boolean
)
language sql
stable
security definer
set search_path = ''
as $$
  select
    r.photo_id,
    r.reaction,
    count(*)::bigint as reaction_count,
    bool_or(r.visitor_id = p_visitor_id) as reacted_by_me
  from public.photo_reactions as r
  where r.photo_id = any(coalesce(p_photo_ids, array[]::text[]))
  group by r.photo_id, r.reaction;
$$;

create or replace function public.toggle_photo_reaction(
  p_photo_id text,
  p_reaction text,
  p_visitor_id uuid
)
returns text
language plpgsql
security definer
set search_path = ''
as $$
declare
  current_reaction text;
begin
  if p_photo_id is null or char_length(p_photo_id) not between 1 and 128 then
    raise exception 'Fotografia inválida';
  end if;

  if p_visitor_id is null then
    raise exception 'Visitante inválido';
  end if;

  if p_reaction not in ('love', 'joy', 'heart_eyes', 'moved', 'celebrate') then
    raise exception 'Reação inválida';
  end if;

  select r.reaction
    into current_reaction
    from public.photo_reactions as r
   where r.photo_id = p_photo_id
     and r.visitor_id = p_visitor_id;

  if current_reaction = p_reaction then
    delete from public.photo_reactions as r
     where r.photo_id = p_photo_id
       and r.visitor_id = p_visitor_id;
    return null;
  end if;

  insert into public.photo_reactions (photo_id, visitor_id, reaction)
  values (p_photo_id, p_visitor_id, p_reaction)
  on conflict (photo_id, visitor_id)
  do update set
    reaction = excluded.reaction,
    updated_at = now();

  return p_reaction;
end;
$$;

revoke all on function public.get_photo_reactions(text[], uuid) from public;
revoke all on function public.toggle_photo_reaction(text, text, uuid) from public;
grant execute on function public.get_photo_reactions(text[], uuid) to anon, authenticated;
grant execute on function public.toggle_photo_reaction(text, text, uuid) to anon, authenticated;
